### ISSUE TITLE
Missing dep: `pcdsutils.qt`

### ISSUE THREAD

**Issue by ronpandolfi** [pcdshub/typhos#264]
Running from d0963fccdcb79a9672ea594224c8c5252010209c, there's a new dep not included in `setup.py`
```
import typhos
Traceback (most recent call last):
  File "/home/rp/PycharmProjects/xi-cam2/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-3f144c8bc1c4>", line 1, in <module>
    import typhos
  File "/opt/pycharm-professional/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/rp/PycharmProjects/typhos/typhos/__init__.py", line 10, in <module>
    from .display import TyphosDeviceDisplay
  File "/opt/pycharm-professional/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/rp/PycharmProjects/typhos/typhos/display.py", line 10, in <module>
    import pcdsutils.qt
  File "/opt/pycharm-professional/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'pcdsutils.qt'
```

**Comment by ronpandolfi** [comment]
Traced the issue to something else. Opening a new issue...
