### ISSUE TITLE
Logging handler (GuiHandler) raising RuntimeError

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#272]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/site-packages/ophyd/sim.py", line 253, in periodic_update
    signal.put(signal._func())
  File "/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/site-packages/ophyd/signal.py", line 203, in put
    value, timestamp, force, metadata
  File "/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/logging/__init__.py", line 1636, in info
    self.log(INFO, msg, *args, **kwargs)
  File "/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/logging/__init__.py", line 1674, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/site-packages/pydm/widgets/logdisplay.py", line 70, in emit
    self.message.emit(self.format(record))
RuntimeError: wrapped C/C++ object of type GuiHandler has been deleted
```

_Originally posted by @ZLLentz in https://github.com/pcdshub/typhos/pull/269#issuecomment-618693488_

**Comment by hhslepicka** [comment]
We should transfer this issue to PyDM and we can address it there.

**Comment by klauer** [comment]
Is it PyDM or how we're using it in Typhos?

**Comment by hhslepicka** [comment]
Almost certainly PyDM but I am checking it here...

**Comment by hhslepicka** [comment]
Fix submitted.
