### ISSUE TITLE
AttributeError: module 'subprocess' has no attribute 'Popen'

### ISSUE THREAD

**Issue by hhslepicka** [pcdshub/typhos#274]
I'm not sure if that is an issue at Typhos or Ophyd yet.
The trace goes back to ophyd and it looks like something related to versioneeer?

## Expected Behavior
No error when opening Typhos screen with Console.

## Current Behavior
```python
Traceback (most recent call last):
  File "/Users/slepicka/mc/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/slepicka/mc/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/slepicka/mc/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/Users/slepicka/mc/envs/py37/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/slepicka/mc/envs/py37/lib/python3.7/site-packages/ipykernel/connect.py", line 10, in <module>
    from subprocess import Popen, PIPE
  File "/Users/slepicka/mc/envs/py37/lib/python3.7/subprocess.py", line 50, in <module>
    import signal
  File "/Users/slepicka/sandbox/git-pcdshub/typhon-git/typhos/signal.py", line 7, in <module>
    from ophyd import Kind
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/__init__.py", line 103, in <module>
    __version__ = get_versions()['version']
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/_version.py", line 507, in get_versions
    pieces = git_pieces_from_vcs(cfg.tag_prefix, root, verbose)
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/_version.py", line 229, in git_pieces_from_vcs
    hide_stderr=True)
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/_version.py", line 79, in run_command
    p = subprocess.Popen([c] + args, cwd=cwd, env=env,
AttributeError: module 'subprocess' has no attribute 'Popen'
```

## Steps to Reproduce (for bugs)
1. Run typhos with an Ophyd sim device: `typhos "ophyd.sim.SynAxis[]"`
2. Observe the terminal.

## Your Environment
<details>
  <summary>conda list</summary>
```
$ conda list
# packages in environment at /Users/slepicka/mc/envs/py37:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.3                    pypi_0    pypi
appnope                   0.1.0           py37hc8dfbb8_1001    conda-forge
attrs                     19.3.0                     py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.4              pyh9f0ad1d_0    conda-forge
bluesky                   1.6.0rc2.post52+g1231a17f           dev_0    <develop>
bokeh                     1.4.0                    py37_0    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
caproto                   0.4.4                    pypi_0    pypi
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cf_units                  2.0.1           py37h917ab60_1002    conda-forge
cffi                      1.14.0           py37h356ff06_0    conda-forge
cfgv                      3.1.0                    pypi_0    pypi
cftime                    1.1.1.2          py37h10e2902_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
cloudpickle               1.3.0                      py_0    conda-forge
codecov                   2.0.15                     py_1    conda-forge
coloredlogs               10.0                  py37_1000    conda-forge
coverage                  5.0.4            py37h9bfed18_0    conda-forge
cryptography              2.8              py37he655712_2    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.16          py37h570ac47_0    conda-forge
cytoolz                   0.10.1           py37h0b31af3_0    conda-forge
dask-core                 2.14.0                     py_0    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distlib                   0.3.0                    pypi_0    pypi
doctr                     1.8.0                      py_0    conda-forge
docutils                  0.16             py37hc8dfbb8_1    conda-forge
edmbutton                 0.3.0                     dev_0    <develop>
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
epics-pypdb               0.1                      pypi_0    pypi
epicscorelibs             7.0.3.99.2.0     py37hb7bd4ab_0    conda-forge
event-model               1.12.0                     py_0    conda-forge
expat                     2.2.9                h4a8c4bd_2    conda-forge
filelock                  3.0.12                   pypi_0    pypi
flake8                    3.7.9                    py37_0    conda-forge
freetype                  2.10.1               h8da9a1a_0    conda-forge
fuzzywuzzy                0.17.0                     py_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
glib                      2.58.3          py37h7c187be_1004    conda-forge
happi                     1.4.0+70.g6865203           dev_0    <develop>
heapdict                  1.0.1                    pypi_0    pypi
helpdev                   0.6.10                   pypi_0    pypi
historydict               1.2.3                      py_0    conda-forge
humanfriendly             8.1              py37hc8dfbb8_1    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
identify                  1.4.11                   pypi_0    pypi
idna                      2.8                      pypi_0    pypi
imageio                   2.8.0                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
ipykernel                 5.2.0            py37h43977f1_1    conda-forge
ipython                   7.10.1           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.16.0           py37hc8dfbb8_1    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json5                     0.9.0                      py_0    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.2                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab                1.2.3                      py_0    conda-forge
jupyterlab_server         1.1.0                      py_1    conda-forge
keyring                   21.0.0                   pypi_0    pypi
kiwisolver                1.2.0            py37ha1cc60f_0    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libclang                  8.0.1                ha1b3eb9_2    conda-forge
libcxx                    10.0.0                        0    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm8                  8.0.1                h770b8ee_0    conda-forge
libopenblas               0.3.9                h3d69b6c_0    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
llvm-openmp               9.0.1                h28b9765_2    conda-forge
lucid                     0.0.0+66.gf566321.dirty           dev_0    <develop>
lxml                      4.5.0                    pypi_0    pypi
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
markupsafe                1.1.1            py37h9bfed18_1    conda-forge
matplotlib                3.1.2                    py37_1    conda-forge
matplotlib-base           3.1.2            py37h11da6c2_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37h0b31af3_1000    conda-forge
mongomock                 3.18.0                     py_0    conda-forge
more-itertools            8.2.0                      py_0    conda-forge
msgpack                   0.6.2                    pypi_0    pypi
msgpack-numpy             0.4.4.3                  pypi_0    pypi
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.4                        py_1    conda-forge
nodeenv                   1.3.5                    pypi_0    pypi
nose                      1.3.7                 py37_1003    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
nspr                      4.20              h0a44026_1000    conda-forge
nss                       3.47                 hc0980d9_0    conda-forge
numpy                     1.17.3           py37hde6bac1_0    conda-forge
numpydoc                  0.9.1                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1f               h0b31af3_0    conda-forge
ophyd                     1.4.0rc3.post9+g39277bd           dev_0    <develop>
p4p                       3.4.2            py37h4f17bb1_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandoc                    2.9.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.6.2                      py_0    conda-forge
pcdsdevices               2.4.0+13.gc8574aeadc           dev_0    <develop>
pcdsutils                 0.0.0                     dev_0    <develop>
pcdswidgets               0.3.0                     dev_0    <develop>
pcre                      8.44                 h4a8c4bd_0    conda-forge
periodictable             1.5.2                      py_0    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pillow                    7.1.1            py37hfd78ece_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pkginfo                   1.5.0.1                  pypi_0    pypi
pluggy                    0.13.0                   py37_0    conda-forge
ply                       3.11                       py_1    conda-forge
pockets                   0.9.1                      py_0    conda-forge
pre-commit                2.2.0                    pypi_0    pypi
prettytable               0.7.2                      py_3    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
prompt_toolkit            3.0.5                         0    conda-forge
psutil                    5.6.7                    pypi_0    pypi
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.1                      py_0    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.20                       py_0    conda-forge
pydm                      1.9.0                     dev_0    <develop>
pyenvbuilder              0.0.0+13.g31f16e4.dirty           dev_0    <develop>
pyepics                   3.4.1                    py37_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pymongo                   3.10.1           py37h4a8c4bd_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py37he22c54c_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtads                   3.2.2            py37h4a8c4bd_0    conda-forge
pyqtgraph                 0.11.0rc0                  py_0    conda-forge
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py37h9bfed18_0    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
pytest                    5.3.1                    py37_0    conda-forge
pytest-cov                2.8.1                      py_0    conda-forge
pytest-qt                 3.3.0                      py_0    conda-forge
pytest-timeout            1.3.3                      py_0    conda-forge
python                    3.7.3                h5c2c468_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-levenshtein        0.12.0          py37h0b31af3_1001    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytmc                     2.5.0                    pypi_0    pypi
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.1.1            py37h3b54f70_0    conda-forge
pyyaml                    5.3.1            py37h9bfed18_0    conda-forge
pyzmq                     19.0.0           py37haec44b1_1    conda-forge
qdarkstyle                2.7                        py_0    conda-forge
qt                        5.12.5               h1b46049_0    conda-forge
qtawesome                 0.6.0                      py_0    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
qtpy                      1.9.0                    pypi_0    pypi
qtpynodeeditor            0.1.0                    pypi_0    pypi
readline                  8.0                  hcfe32e1_0    conda-forge
readme-renderer           24.0                     pypi_0    pypi
requests                  2.22.0                   pypi_0    pypi
requests-toolbelt         0.9.1                    pypi_0    pypi
scikit-image              0.16.2           py37h4f17bb1_0    conda-forge
scikit-learn              0.22             py37h3dc85bc_1    conda-forge
scipy                     1.3.2            py37h82752d6_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
sentinels                 1.0.0                      py_1    conda-forge
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
simplejson                3.17.0           py37h0b31af3_0    conda-forge
sip                       4.19.18          py37h4a8c4bd_1    conda-forge
six                       1.14.0                     py_1    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sphinx                    2.2.2                      py_0    conda-forge
sphinx_rtd_theme          0.4.3                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-napoleon    0.7                        py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
super_state_machine       2.0.2                 py37_1000    conda-forge
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
timechart                 1.2.3                     dev_0    <develop>
tk                        8.6.10               hbbe82c9_0    conda-forge
toml                      0.10.0                   pypi_0    pypi
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py37h9bfed18_1    conda-forge
tqdm                      4.40.2                     py_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
twine                     3.1.1                    pypi_0    pypi
typhos                    0.6.0+11.gdb212b9           dev_0    <develop>
udunits2                  2.2.27.6          h776b7f1_1001    conda-forge
urllib3                   1.25.7                   pypi_0    pypi
versioneer                0.18                     pypi_0    pypi
virtualenv                20.0.11                  pypi_0    pypi
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
xz                        5.2.5                h0b31af3_0    conda-forge
yaml                      0.2.2                h0b31af3_1    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zict                      1.0.0                    pypi_0    pypi
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                hed8d7c8_2    conda-forge

```
</details>

**Comment by klauer** [comment]
That's a strange one - looks like the jupyter console kernel subprocess.

**Comment by klauer** [comment]
Only thing I can think of - do you by chance have a `subprocess.py` file in your working directory when running `typhos`?

**Comment by ZLLentz** [comment]
Alternatively: do you have a `signal.py` in your working directory? The Python subprocess library should not import from typhos.signal.

```
  File "/Users/slepicka/mc/envs/py37/lib/python3.7/subprocess.py", line 50, in <module>
    import signal
  File "/Users/slepicka/sandbox/git-pcdshub/typhon-git/typhos/signal.py", line 7, in <module>
    from ophyd import Kind
```

**Comment by klauer** [comment]
Ahh, that's it, @ZLLentz. We should rename `typhos.signal`.

**Comment by hhslepicka** [comment]
Ooooops... I was running my code at a bad folder! :(

**Comment by ZLLentz** [comment]
and `pcdsdevices.signal`
