### ISSUE TITLE
Regression with ImageButton

### ISSUE THREAD

**Issue by hhslepicka** [pcdshub/typhos#288]
## Expected Behavior
2D array data should show Image Button.

## Current Behavior
It is showing a text edit and a label with the array in it.

## Steps to Reproduce (for bugs)
1. Open a typhos display with a camera
2. Enable the Omitted Signals
3. Look for the shaped_image signal and note the entry.

## Context
This seems to be a regression caused by #282 . I need to investigate further.

**Comment by klauer** [comment]
The dimension check is here: https://github.com/pcdshub/typhos/blob/6b40799bf9f2d6d42dfde07105cb325dad57e6d6/typhos/widgets.py#L549

Is it possible the camera hadn't acquired a frame or `shaped_image` was empty or something?

**Comment by hhslepicka** [comment]
IOC-wise, the camera was on free run and acquiring for a while... maybe a race between connection and filling the metadata?

**Comment by hhslepicka** [comment]
I was able to get an error message with the logging system:
```
ERROR:Subscription value callback exception (EpicsSignal(read_pv='13SIM1:image1:ArrayData', name='sample_camera_image_array_data', parent='sample_camera_image', value=array([0, 0, 0, ..., 0, 0, 0], dtype=uint8), timestamp=1588615369.09591, auto_monitor=False, string=False, write_pv='13SIM1:image1:ArrayData', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/device.py", line 223, in __get__
    return instance._signals[self.attr]
KeyError: 'shaped_image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/signal.py", line 587, in _derived_value_callback
    value = self.inverse(value)
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/areadetector/base.py", line 105, in inverse
    array_shape = self.derived_shape[:self.derived_ndims]
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/areadetector/base.py", line 85, in derived_shape
    for dim in self._shape:
AttributeError: 'NDDerivedSignal' object has no attribute '_shape'
ERROR:Subscription value callback exception (EpicsSignal(read_pv='13SIM1:image1:ArrayData', name='sample_camera_image_array_data', parent='sample_camera_image', value=array([0, 0, 0, ..., 0, 0, 0], dtype=uint8), timestamp=1588615369.09591, auto_monitor=False, string=False, write_pv='13SIM1:image1:ArrayData', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/signal.py", line 587, in _derived_value_callback
    value = self.inverse(value)
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/areadetector/base.py", line 105, in inverse
    array_shape = self.derived_shape[:self.derived_ndims]
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/areadetector/base.py", line 85, in derived_shape
    for dim in self._shape:
AttributeError: 'NDDerivedSignal' object has no attribute '_shape'
DEBUG:Instantiating a not-yet-created signal from a component: sample_camera_image_shaped_image
```

I will investigate a bit more
