### ISSUE TITLE
SystemError with TyphosPositionerWidget and Python > 3.7.3

### ISSUE THREAD

**Issue by hhslepicka** [pcdshub/typhos#354]
## Expected Behavior
No error when using the widget with Python > 3.7.3

## Current Behavior
```python
$ ipython --gui qt
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from typhos.positioner import TyphosPositionerWidget
Warning: QApplication was created before pyqtgraph was imported; there may be problems (to avoid bugs, call QApplication.setGraphicsSystem("raster") before the QApplication is created).

In [2]: w = TyphosPositionerWidget()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-2-68004ea9ab29> in <module>
----> 1 w = TyphosPositionerWidget()

~/sandbox/git-pcdshub/typhon-git/typhos/positioner.py in __init__(self, parent)
    148         super().__init__(parent=parent)
    149
--> 150         self.ui = uic.loadUi(self.ui_template, self)
    151         self.ui.set_value.returnPressed.connect(self.set)
    152         self.ui.tweak_positive.clicked.connect(self.positive_tweak)

~/mc/envs/py37/lib/python3.7/site-packages/PyQt5/uic/__init__.py in loadUi(uifile, baseinstance, package, resource_suffix)
    225     from .Loader.loader import DynamicUILoader
    226
--> 227     return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
    228
    229

~/mc/envs/py37/lib/python3.7/site-packages/PyQt5/uic/Loader/loader.py in loadUi(self, filename, toplevelInst, resource_suffix)
     70             basedir = os.path.dirname(filename)
     71
---> 72         return self.parse(filename, resource_suffix, basedir)

~/mc/envs/py37/lib/python3.7/site-packages/PyQt5/uic/uiparser.py in parse(self, filename, resource_suffix, base_dir)
   1028             elem = document.find(tagname)
   1029             if elem is not None:
-> 1030                 actor(elem)
   1031         self.finalize()
   1032         w = self.toplevelWidget

~/mc/envs/py37/lib/python3.7/site-packages/PyQt5/uic/uiparser.py in createConnections(self, elem)
    940                     bound_signal[tuple(signal_args)].connect(slot)
    941
--> 942         QtCore.QMetaObject.connectSlotsByName(self.toplevelWidget)
    943
    944     def customWidgets(self, elem):

SystemError: <built-in function connectSlotsByName> returned a result with an error set

```
## Possible Solution
PR coming up...

## Steps to Reproduce (for bugs)
Describe above.

## Context
Can't use TyphosPositionerWidget with Python > 3.7.3

**Comment by klauer** [comment]
Saw this with a slightly different error at the bottom that made it seem like it was something else:

```
SystemError: <built-in function connectSlotsByName> returned a result with an error set
```

then
```
Traceback (most recent call last):
  File "/Users/klauer/docs/Repos/typhos/typhos/display.py", line 424, in _template_selected
    self.device_display.force_template = template
  File "/Users/klauer/docs/Repos/typhos/typhos/display.py", line 936, in force_template
    self.load_best_template()
  File "/Users/klauer/docs/Repos/typhos/typhos/display.py", line 851, in load_best_template
    if widget:
UnboundLocalError: local variable 'widget' referenced before assignment
```

What's the appropriate fix here?

**Comment by hhslepicka** [comment]
I chased this error for a while when I was working at the `Split between core and devices` PR. I could not find a clear source of the issue as I could with the same error at the PyDMImage widget.
Before I could issue a breakpoint at `connectSlotsByName` and step into the problematic part, which often was access to a variable via a `Property` that was not yet available by the class but with no lucky yet for the Positioner. On the interest of time I put that aside to finish the tests and get it working with Python <= 3.7.3.

The issue with the `UnboundLocalError` I can't find a case in which the `widget` variable would not be defined. 
If you can reproduce that, do you mind sending the steps?

**Comment by ZLLentz** [comment]
This was fixed at some point
