### ISSUE TITLE
Exception raised on close

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhos#486]
## Expected Behavior

Program should exit cleanly

## Current Behavior

```
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fd92d8c2700>
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/asyncio/base_events.py", line                                                                                            688, in __del__
    self.close()
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/asyncio/unix_events.py", line                                                                                            58, in close
    super().close()
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/asyncio/selector_events.py", l                                                                                           ine 87, in close
    self._close_self_pipe()
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/asyncio/selector_events.py", l                                                                                           ine 94, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/asyncio/selector_events.py", l                                                                                           ine 272, in _remove_reader
    key = self._selector.get_key(fd)
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/selectors.py", line 191, in ge                                                                                           t_key
    return mapping[fileobj]
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/selectors.py", line 72, in __g                                                                                           etitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/selectors.py", line 226, in _f                                                                                           ileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/selectors.py", line 42, in _fi                                                                                           leobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
```
## Steps to Reproduce (for bugs)

1. Open a screen
2. Close the screen using the x in the corner

## Context

Just annoying

## Your Environment

pcds-5.3.1

**Comment by tangkong** [comment]
Stale, and I cannot reproduce this.  Surely this is fixed...
