### ISSUE TITLE
Invalid icon name for font

### ISSUE THREAD

**Issue by anleslac** [pcdshub/typhos#489]
## Expected Behavior

No font errors

## Current Behavior

Error as soon as typhos display is launched:
```
Traceback (most recent call last):
  File "C:\Users\anle\PycharmProjects\typhos\typhos\suite.py", line 624, in from_devices
    suite.add_tool(name, tool())
  File "C:\Users\anle\PycharmProjects\typhos\typhos\tools\plot.py", line 55, in __init__
    self.timechart = TimeChartDisplay(show_pv_add_panel=False)
  File "C:\Users\anle\Miniconda3\envs\typhos\lib\site-packages\timechart\displays\main_display.py", line 152, in __init__
    self.reset_icon = IconFont().icon("circle-o-notch",
  File "C:\Users\anle\Miniconda3\envs\typhos\lib\site-packages\pydm\utilities\iconfont.py", line 97, in icon
    char = self.get_char_for_name(name)
  File "C:\Users\anle\Miniconda3\envs\typhos\lib\site-packages\pydm\utilities\iconfont.py", line 72, in get_char_for_name
    raise ValueError("Invalid icon name for font.")
ValueError: Invalid icon name for font.
```

## Steps to Reproduce (for bugs)

Run the Getting Started code:
```py
import sys
from ophyd.sim import motor
from qtpy.QtWidgets import QApplication
import typhos

# Create our application
app = QApplication.instance() or QApplication(sys.argv)
typhos.use_stylesheet()  # Optional
suite = typhos.TyphosSuite.from_device(motor)

# Launch
suite.show()
app.exec_()
```

## Context

I am trying to learn the basics of typhos.

## Your Environment

On Windows with Miniconda3:
```
conda create -n typhos python=3.8
pip install -r requirements.txt
pip install pyqt5
```

EDIT: The problem goes away if I install typhos via conda:
```
conda create -n typhos python=3.8
conda activate typhos
conda install typhos -c conda-forge -c pcds-tag
```

**Comment by klauer** [comment]
I think the font names come from `fontawesome` which is packaged by PyDM.

Can you compare your PyDM versions between the two environments?

https://github.com/slaclab/pydm/blob/5740b1a57c9c7870df26f2d5b898e345a104f423/pydm/utilities/iconfont.py#L24-L25

**Comment by anleslac** [comment]
Both PyDM versions are the same.

**Comment by klauer** [comment]
It looks like our typhos build on PyPI is _very_ out of date! Let me update that and have you try again in a few minutes.

**Comment by anleslac** [comment]
After your fixes, the error is gone. Thank you so much!

**Comment by klauer** [comment]
Thanks, @anleslac!
