### ISSUE TITLE
Positioner widget uncaught type error in `_link_limits_by_limits_attr` (fee_m2h)

### ISSUE THREAD

**Issue by klauer** [pcdshub/typhos#565]
## Current Behavior
```
[2023-08-08 13:59:35] - ERROR - Unable to add 'fee_m2h' to TyphosSuite
Traceback (most recent call last):
  File "/cds/home/k/klauer/Repos/typhos/typhos/suite.py", line 734, in from_devices
    suite.show_subdisplay(device)
  File "/cds/home/k/klauer/Repos/typhos/typhos/suite.py", line 440, in show_subdisplay
    widget = self.get_subdisplay(widget)
  File "/cds/home/k/klauer/Repos/typhos/typhos/suite.py", line 421, in get_subdisplay
    subdisplay = subdisplay()
  File "/cds/home/k/klauer/Repos/typhos/typhos/display.py", line 1531, in from_device
    display.add_device(device, macros=macros)
  File "/cds/home/k/klauer/Repos/typhos/typhos/display.py", line 1416, in add_device
    self.load_best_template()
  File "/cds/home/k/klauer/Repos/typhos/typhos/display.py", line 1298, in load_best_template
    self._update_children()
  File "/cds/home/k/klauer/Repos/typhos/typhos/display.py", line 1348, in _update_children
    widget.add_device(device)
  File "/cds/home/k/klauer/Repos/typhos/typhos/panel.py", line 750, in add_device
    self._panel_layout.add_device(device)
  File "/cds/home/k/klauer/Repos/typhos/typhos/panel.py", line 857, in add_device
    self.add_sub_device(sub_device, name=dotted_name)
  File "/cds/home/k/klauer/Repos/typhos/typhos/panel.py", line 842, in add_sub_device
    container.add_device(device)
  File "/cds/home/k/klauer/Repos/typhos/typhos/display.py", line 1416, in add_device
    self.load_best_template()
  File "/cds/home/k/klauer/Repos/typhos/typhos/display.py", line 1298, in load_best_template
    self._update_children()
  File "/cds/home/k/klauer/Repos/typhos/typhos/display.py", line 1348, in _update_children
    widget.add_device(device)
  File "/cds/home/k/klauer/Repos/typhos/typhos/positioner.py", line 698, in add_device
    super().add_device(device)
  File "/cds/home/k/klauer/Repos/typhos/typhos/positioner.py", line 422, in add_device
    self._link_limits_by_limits_attr()
  File "/cds/home/k/klauer/Repos/typhos/typhos/positioner.py", line 319, in _link_limits_by_limits_attr
    if low_limit < high_limit:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

Limits can be `None`

**Comment by klauer** [comment]
Given that this happens in `add_device`, it actually breaks the suite.
The typhos CLI doesn't exit early even with `--exit-after` and just hangs.

**Comment by ZLLentz** [comment]
Note that the IOC here doesn't actually exist- the IOC is gone and is completely replaced by a new one. The happi entry is correspondingly marked as inactive.
```
$ happi search fee_m2h
+--------------------+--------------------------------------------------------------------------------------------+
| EntryInfo          | Value                                                                                      |
+--------------------+--------------------------------------------------------------------------------------------+
| active             | False                                                                                      |
| args               | ['{{prefix}}']                                                                             |
| beamline           | HXD                                                                                        |
| creation           | Tue Feb 27 16:00:54 2018                                                                   |
| detailed_screen    | None                                                                                       |
| device_class       | pcdsdevices.device_types.OffsetMirror                                                      |
| documentation      | None                                                                                       |
| embedded_screen    | None                                                                                       |
| engineering_screen | None                                                                                       |
| functional_group   | N/A                                                                                        |
| input_branches     | None                                                                                       |
| ioc_arch           | None                                                                                       |
| ioc_engineer       | None                                                                                       |
| ioc_hutch          | None                                                                                       |
| ioc_location       | None                                                                                       |
| ioc_name           | None                                                                                       |
| ioc_release        | None                                                                                       |
| ioc_type           | None                                                                                       |
| kwargs             | {'name': '{{name}}', 'prefix_xy': '{{prefix_xy}}', 'xgantry_prefix': '{{xgantry_prefix}}'} |
| last_edit          | Wed Feb 22 15:44:46 2023                                                                   |
| lightpath          | False                                                                                      |
| location_group     | N/A                                                                                        |
| macros             | None                                                                                       |
| name               | fee_m2h                                                                                    |
| output_branches    | None                                                                                       |
| parent             | None                                                                                       |
| pitch_ranges       | None                                                                                       |
| prefix             | FEE1:M2H                                                                                   |
| prefix_xy          | STEP:M2H                                                                                   |
| screen             | None                                                                                       |
| stand              | None                                                                                       |
| system             | beam control                                                                               |
| type               | pcdsdevices.happi.containers.OffsetMirror                                                  |
| x_ranges           | None                                                                                       |
| xgantry_prefix     | STEP:FEE1:861:MOTR                                                                         |
| y_ranges           | None                                                                                       |
| z                  | 751.84300                                                                                  |
+--------------------+--------------------------------------------------------------------------------------------+
```
